jwt:
  secretKey: ENC(5gkoNklMBSd4eAujzr+i+haIuwMU/kZ7)

  access:
    expiration: 1800000 # 30? (1000L(ms -> s) * 60L(s -> m) * 30L
#    expiration: 180000 # 30? (1000L(ms -> s) * 60L(s -> m) * 30L

  refresh:
    expiration: 604800000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> D) * 7(1D))


jasypt:
  encryptor:
    password: ${PASSWORD}