spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.39.110.134:3306/bank
#    url: jdbc:mysql://localhost:3300/bank
    username: root
    password: qwe123
#    password: 1234

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: true
    hibernate:
      ddl-auto: update

  http:
    auth-token-header:
      name: Authorization

    auth-token: ssafy_d210_bankserver

  redis:
#    host: 172.18.0.4
    host: 3.39.110.134
    port: 6379

  kafka:
    producer:
      bootstrap-servers: j9d210.p.ssafy.io:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8083